apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  rules:
  {{- $releaseName := .Release.Name }}
  {{- $chartName := .Chart.Name }}
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $releaseName }}-{{ $chartName }}
            port:
              number: 7777
  {{- end }}
  tls:
  - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . }}
      {{- end }}
    secretName: {{ $releaseName }}-{{ $chartName }}-tls