apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.strfry_log]
    type = "file"
    include = ["/app/logs/strfry.log"]
    read_from = "beginning"

    [transforms.parse_log]
    type = "remap"
    inputs = ["strfry_log"]
    source = '''
    parsed, err = parse_json(.message)
    if err == null {
      . = parsed
    }
    '''

    [transforms.filter_errors]
    type = "filter"
    inputs = ["parse_log"]
    condition = '''
    exists(.level) && .level == "error"
    '''

    [transforms.format_event]
    type = "remap"
    inputs = ["filter_errors"]
    source = '''
    event = {
      "level": .level,
      "message": .message,
      "service": "strfry",
      "timestamp": to_string(now())
    }
    . = encode_json(event)
    '''

    [sinks.console]
    type = "console"
    inputs = ["format_event"]
    encoding.codec = "text"

    [sinks.honeycomb_raw]
    type = "http"
    inputs = ["format_event"]
    uri = "https://api.honeycomb.io/1/events/strfry-relay-logs"
    method = "post"
    compression = "none"

    encoding.codec = "text"
    batch.max_events = 1
    batch.timeout_secs = 1

    [sinks.honeycomb_raw.request]
    headers.X-Honeycomb-Team = "{{ .Values.honeycomb.apiKey }}"
    headers.Content-Type = "application/json"
    timeout_secs = 30
