{{- if .Values.galoy.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "galoy.api.fullname" . }}-healthz
  labels:
    app: {{ template "galoy.api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.galoy.api.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600" # 1 hour
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600" # 1 hour
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1s"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/limit-rpm: "60"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "40"
    nginx.ingress.kubernetes.io/limit-connections: "80"
    nginx.ingress.kubernetes.io/cors-allow-methods: POST
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.galoy.api.flashPay.hostname }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- with .Values.galoy.api.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    {{- range .Values.galoy.api.ingress.hosts }}
    - hosts:
      - {{ . }}
      secretName: {{ printf "%s-tls" . }}
    {{- end }}
  rules:
  {{- range .Values.galoy.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /healthz
          backend:
            service:
              name: {{ template "galoy.api.fullname" $ }}
              port:
                number: {{ $.Values.galoy.api.port }}
  {{- end -}}
{{- end -}}