apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nostr-multiplexer.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  {{- if .Values.ingress.enabled }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /(.well-known/nostr.json)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  multiplexer-release-nostr-multiplexer
            port:
              number: 4000
  {{- end }}
  {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}