apiVersion: v2
name: loop
type: application
version: 0.2.0
appVersion: 0.20.1
description: A Helm chart for Kubernetes
keywords:
  - loop
maintainers:
  - name: dread
    email: dread@getflash.io
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.6.0
  - name: loopserver
    version: x.x.x
    condition: loopserver.enabled
