galoy:
  network: regtest
  api:
    replicas: 1
    ingress:
      enabled: true
      hosts: ["api.staging.flashapp.me", "localhost"]
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      extraPaths:
        - path: /(graphql|kratos|browser|healthz|metrics|auth)
          pathType: ImplementationSpecific
          backend:
            service:
              name: api
              port:
                number: 4002
  admin:
    ingress:
      enabled: true
      hosts: ["admin.staging.flashapp.me", "localhost"]
      annotations:
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      extraPaths:
        - path: /admin/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: graphql-admin
              port:
                number: 4001

mongodb:
  architecture: standalone
  persistence:
    enabled: false
  replicaCount: 1
  metrics:
    enabled: false
  initDbScripts: {}

redis:
  replica:
    replicaCount: 1
  master:
    persistence:
      enabled: false
  metrics:
    enabled: false
  sentinel:
    getMasterTimeout: 5

price:
  postgresql:
    primary:
      persistence:
        enabled: false

oathkeeper:
  replicaCount: 1
  secret:
    enabled: false

kratos:
  replicaCount: 1
