name: Deploy Flash

on:
  push:
    branches:
      - doc

jobs:
  build:
    env:
      CLUSTER_NAME: flash-cluster
      CHART_NAME: .
      RELEASE_NAME: flash
      NAMESPACE: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Save DigitalOcean Kubernetes credentials
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show $CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig
      - name: Set kubeconfig permissions
        run: sudo chmod 600 $GITHUB_WORKSPACE/.kubeconfig

      - name: Add Galoy Helm repository
        run: helm repo add galoy https://GaloyMoney.github.io/charts

      - name: Install/upgrade charts in specified order
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: "1.18.0"
          helm: "3.12.3"
          command: |
            charts=(
              ./charts/bitcoind
              ./charts/lnd
              # ./charts/mempool
              # ./charts/fulcrum
              # ./charts/loop
              # ./charts/loop
              # ./charts/kafka-connect
              # ./charts/specter
              # ./charts/galoy-deps
              # ./charts/monitoring
              # ./charts/galoy
            )

            for dir in "${charts[@]}"; do
              chart_name=$(basename $dir)
              release="${RELEASE_NAME}-${chart_name}"
              helm dep update $dir
              helm upgrade --install --namespace $NAMESPACE --create-namespace --kubeconfig $GITHUB_WORKSPACE/.kubeconfig $release $dir
            done

      - name: Delete unwanted Helm releases
        uses: stefanprodan/kube-tools@v1
        env:
          KUBECONFIG: $GITHUB_WORKSPACE/.kubeconfig
        with:
          kubectl: "1.18.0"
          helm: "3.12.3"
          command: |
            unwanted_releases=(
              "flash-admin-panel-7ffb95c94d-lgksf"
              "flash-fulcrum-0"
              "flash-galoy-deps-cert-manager-54d4dcb968-nsxzf"
              "flash-galoy-deps-cert-manager-cainjector-dc866d4b7-zmp8t"
              "flash-galoy-deps-cert-manager-webhook-5b75bd46c-rdsr9"
              "flash-galoy-deps-ingress-nginx-controller-667846f448-2dw"
              "flash-galoy-deps-ingress-nginx-controller-667846f448-gxxml"
              "flash-galoy-deps-opentelemetry-collector-9f7f445cf-snjt7"
              "flash-loop-0"
              "flash-loopserver-0"
              "flash-mempool-0"
              "flash-monitoring-grafana-65796469b9-w7zv7"
              "flash-monitoring-kube-state-metrics-848b965df-89kjl"
              "flash-monitoring-prometheus-node-exporter-n65rb"
              "flash-monitoring-prometheus-server-0"
              "flash-rtl-bbdc48558-dm8r8"
              "flash-specter-0"
              "kafka-connect-5c974699d-62jl6"
              "kafka-entity-operator-795dbcc785-mtphg"
              "kafka-kafka-0"
              "kafka-kafka-1"
              "kafka-kafka-2"
              "kafka-zookeeper-0"
              "kafka-zookeeper-1"
              "kafka-zookeeper-2"
              "kubemonkey-787c459787-97qt8"
            )

            for release in "${unwanted_releases[@]}"; do
              helm uninstall --namespace $NAMESPACE $release || true
            done
