name: Deploy Flash
on:
  push:
    branches:
      - doc

jobs:
  build:
    env:
      CLUSTER_NAME: flash-cluster
      CHART_NAME: .
      RELEASE_NAME: flash
      NAMESPACE: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save DigitalOcean Kubernetes credentials
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show $CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig

      - name: List all Helm charts directories
        id: list-charts
        run: |
          echo "::set-output name=charts::$(find ./charts/bitcoind -name Chart.yaml | xargs -n 1 dirname | tr '\n' ' ')"

      - name: Helm install/upgrade charts
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: "1.18.0"
          helm: "3.2.4"
          command: |
            helmv3 repo add galoy https://GaloyMoney.github.io/charts
            for dir in ${{ steps.list-charts.outputs.charts }}; do
              helmv3 dep update $dir
              helmv3 upgrade --install --namespace $NAMESPACE --create-namespace --kubeconfig $GITHUB_WORKSPACE/.kubeconfig $RELEASE_NAME-$dir $dir
            done
