name: Deploy Flash

on:
  push:
    branches:
      - doc

jobs:
  build:
    env:
      CLUSTER_NAME: flash-cluster
      CHART_NAME: .
      RELEASE_NAME: flash
      NAMESPACE: default
      GALOY_NAMESPACE: galoy
      GALOY_DEPS_NAMESPACE: galoy-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Save DigitalOcean Kubernetes credentials
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show $CLUSTER_NAME > $GITHUB_WORKSPACE/.kubeconfig
      - name: Set kubeconfig permissions
        run: sudo chmod 600 $GITHUB_WORKSPACE/.kubeconfig

      - name: Add Galoy Helm repository
        run: helm repo add flash https://lnflash.github.io/charts

      - name: Install/upgrade charts in specified order
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: "1.18.0"
          helm: "3.12.3"
          command: |
            charts=(
              ./charts/galoy-deps
              ./charts/kafka-connect
              ./charts/bitcoind
              ./charts/lnd
              ./charts/loop
              ./charts/galoy
              # ./charts/monitoring
            )
            for dir in "${charts[@]}"; do
              chart_name=$(basename $dir)
              release="${chart_name}"
              helm dep update $dir
              if [ "$dir" == "./charts/galoy" ]; then
                helm upgrade --install --namespace $GALOY_NAMESPACE --create-namespace --kubeconfig $GITHUB_WORKSPACE/.kubeconfig $release $dir --debug
              elif [ "$dir" == "./charts/galoy-deps" ]; then
                helm upgrade --install --namespace $GALOY_DEPS_NAMESPACE --create-namespace --kubeconfig $GITHUB_WORKSPACE/.kubeconfig $release $dir
              else
                helm upgrade --install --namespace $NAMESPACE --create-namespace --kubeconfig $GITHUB_WORKSPACE/.kubeconfig $release $dir
              fi
            done
