name: dev-smoketest
on:
  pull_request:
    branches: [main]

concurrency:
  group: dev-smoketest-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  smoketest:
    name: Hit smoketests against Charts in Dev Setup
    runs-on: self-hosted
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create k3d Cluster
        run: |
          k3d cluster create --image rancher/k3s:v1.27.4-k3s1 \
            -v "$(pwd):/charts" \
            --k3s-arg --disable=traefik@server:0 \
            --k3s-arg --disable=servicelb@server:0
      - name: Deploy Flash Dependencies
        run: |
          pushd dev && source ./.envrc
          make init
          make deploy-services
      - name: Deploy Flash Charts
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 2
          command: pushd dev && source ./.envrc && make deploy
      - name: Flash API Smoketest
        timeout-minutes: 10
        run: |
          pushd dev && source ./.envrc
          kubectl -n galoy-dev-smoketest exec smoketest -- bash -c "cd /charts/ci/tasks && \
            CHART=galoy ./dev-smoketest-settings.sh && \
            ./galoy-smoketest.sh && \
            rm -rf smoketest-settings"
      - name: Flash Pay Smoketest
        timeout-minutes: 5
        run: |
          pushd dev && source ./.envrc
          kubectl -n galoy-dev-smoketest exec smoketest -- bash -c "cd /charts/ci/tasks && \
            CHART=galoy-pay ./dev-smoketest-settings.sh && \
            ./galoy-pay-smoketest.sh && \
            rm -rf smoketest-settings"
      - name: Nostr Rollout Check
        timeout-minutes: 5
        run: |
          kubectl -n galoy-dev-nostr rollout status deployment/multiplexer-release-nostr-multiplexer --timeout=5m
          kubectl -n galoy-dev-nostr rollout status deployment/strfry --timeout=5m
      - name: Debug Cluster State
        if: failure()
        timeout-minutes: 5
        run: |
          kubectl get namespaces
          kubectl get pods --all-namespaces -o wide
          kubectl get events --all-namespaces --sort-by=.lastTimestamp | tail -n 100
      - name: Clean Up
        if: always()
        timeout-minutes: 5
        run: |
          rm -rf ci/tasks/smoketest-settings
          k3d cluster delete --all
