{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "galoyPay.fullname" . }}
  labels:
    app: {{ include "galoyPay.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    {{- if .Values.ingress.rulesOverride }}
      {{- toYaml .Values.ingress.rulesOverride | nindent 4 }}
    {{- else }}
      {{- range .Values.ingress.hosts }}
      - host: {{ .host }}
        http:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "galoyPay.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
      {{- end -}}
    {{- end -}}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ .host }}
      secretName: {{ printf "%s-tls" . }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
{{- end }}
